## cachematrix - R functions to compute and cache inverse of a Matrix
##
## Written by John Kinsella for Coursera class "R Programming"
##

## Function representing a matrix object
## capable of caching it's inverse value
##
## Usage:
##   myMatrix <- makeCacheMatrix(x)
## Arguments:
##   x - matrix value to initially store
## Returns:
##   Returns a list of 4 functions related to the matrix:
##   * set(newValue) - set new value for matrix
##   * get() - get the current matrix value
##   * setInverse(inverseMatrix) - set the inverse matrix value
##   * getInverse() - get the inverse of current matrix if set, NULL otherwise
makeCacheMatrix <- function(x = matrix()) {
  inverseMatrix <- NULL

  set <- function(newValue) {
    x <<- newValue
    inverseMatrix <<- NULL
  }
  get <- function() x
  setinverse <- function(targetInverse) inverseMatrix <<- targetInverse
  getinverse <- function() inverseMatrix

  list(set=set, get=get, setinverse=setinverse, getinverse=getinverse)
}

## Computes inverse of matrix. If inverse was already calculated, returns cached
## value.
##
## Usage:
##   invertedMatrix <- cacheSolve(x)
## Arguments:
##   x - list generated by makeCacheMatrix()
## Returns:
##   inverted version of matrix in x.
cacheSolve <- function(x, ...) {
  inverseMatrix <- x$getinverse()

  # If matrix inverse has been calculated, returned cached value
  if(!is.null(inverseMatrix)) {
    message("Getting cached data")
    return(inverseMatrix)
  }

  # If not cached already, calculate inverse and return
  data <- x$get()
  inverseMatrix <- solve(data)
  x$setinverse(inverseMatrix)
  inverseMatrix
}
